version: '3.3'
services:
  db:
    container_name: anacapa_pg
    restart: on-failure:10
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  jenkins:
    build: ./docker/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
      - jenkins-user
      - jenkins-pass
  anacapa:
    container_name: anacapa_rails
    build:
      context: .
      dockerfile: ./docker/anacapa/Dockerfile
    command: sh ./docker/anacapa/docker-entrypoint.sh
    volumes:
      - .:/anacapa
    ports:
      - "3000:3000"
    depends_on:
      - db
      - jenkins
volumes:
  db-data:
secrets:
  jenkins-user:
    file: ./docker/secrets/jenkins-user.txt
  jenkins-pass:
    file: ./docker/secrets/jenkins-pass.txt
