# config/app.yml for rails-settings-cached
defaults: &defaults
  discoverable: false
  instructors: []
  course_setup: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
